name: Linting

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.5.3"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "plugin"
